version: '2'
networks:
  default:
    external:
      name: ctf_nw

services:
  custom_dns:
    build: dns-bind9
    image: dns-bind9
    volumes:
            - ./dns-bind9/db.0ffs3c-sk1llz:/etc/bind/db.0ffs3c-sk1llz            
            - ./dns-bind9/db.10:/etc/bind/db.10
            - ./dns-bind9/named.conf.local:/etc/bind/named.conf.local
    hostname: vm2-dns
    networks:
     default:
      ipv4_address: 10.10.10.2

  docker_flask:
    build: docker-flask
    image: docker-flask
    hostname: vm3-flask
    dns: 10.10.10.2
    dns_search: 0ffs3c-sk1llz.com
    networks:
     default:
      ipv4_address: 10.10.10.3

  pwnedhub:
    build: pwnedhub
    image: pwnedhub
    hostname: vm4-pwnedhub
    dns: 10.10.10.2
    dns_search: 0ffs3c-sk1llz.com
    networks:
     default:
      ipv4_address: 10.10.10.4
  
  unickle:
    build: unickle
    image: unickle
    hostname: vm5-unickle
    dns: 10.10.10.2
    dns_search: 0ffs3c-sk1llz.com
    networks:
     default:
      ipv4_address: 10.10.10.5

  lamp:
    build: lamp
    image: lamp
    hostname: vm6-lamp
    dns: 10.10.10.2
    dns_search: 0ffs3c-sk1llz.com
    volumes:
            - ./lamp/www:/var/www/html  
    networks:
     default:
      ipv4_address: 10.10.10.6

  lamp-2:
    build: lamp
    image: lamp
    hostname: vm7-lamp
    dns: 10.10.10.2
    dns_search: 0ffs3c-sk1llz.com
    volumes:
            - ./lamp/lab3:/var/www/html  
    networks:
     default:
      ipv4_address: 10.10.10.7
